include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for DAWN
LUCI_DEPENDS:=+luci +dawn +luci-lib-json +luci-lib-httpclient +luci-compat
LUCI_PKGARCH:=all

include luci.mk

# call BuildPackage - OpenWrt buildroot signature
